export function SharedContent() {
  return (
    <>
      <h1>Sign In with Farcaster + NextAuth</h1>
      <p>
        This example app shows how to use{" "}
        <a
          href="https://docs.farcaster.xyz/developers/siwf"
          target="_blank" rel="noreferrer"
        >
          Sign In with Farcaster
        </a>{" "}
        and{" "}
        <a href="https://next-auth.js.org/" target="_blank" rel="noreferrer">
          NextAuth.js
        </a>
        .{" "}<br/>
        On web, SIWF is generated by the{" "}
        <a
          href="https://docs.farcaster.xyz/auth-kit/"
          target="_blank" rel="noreferrer"
        >
          @farcaster/auth-kit
        </a>{" "}
        package and as a mini app it uses the{" "}
        <a
          href="https://miniapps.farcaster.xyz/docs/getting-started#manual-setup"
          target="_blank" rel="noreferrer"
        >
          @farcaster/miniapp-sdk
        </a>{" "}
        package.
      </p>
    </>
  );
}
